<Workspace Version="1.3.3.4111" X="-99.6058617425459" Y="310.081947885864" zoom="0.535440865476314" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="String" resolvedName="DSCore.String" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="DSCore.List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="70184cf9-9ce0-4d09-b557-b0db93f923ba" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Material.ByName" x="602.034381782356" y="187.314471884254" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Material.ByName@string">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="8ee843eb-5013-469a-911f-b0f992169a28" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="283.078054554878" y="186.980972978507" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;f1_kalkzandsteen&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="c4dbb2f2-6e0a-49c1-afbd-296a32d6b610" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Material.MaterialAssetElement" x="874.600496549735" y="515.196328758352" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="9ff6d455-1fc0-4d6d-95d8-15b373035e78" />
      <Name value="Material.MaterialAssetElement" />
      <Description value="This node retrieves a Material Asset Element from Material. If such is not defined it will return an Invalid Element Id (-1)" />
      <Inputs>
        <Input value="Material" />
      </Inputs>
      <Outputs>
        <Output value="MaterialAssetElement" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="f4501bc2-b4e5-4a31-9cd9-cf02b2b1c693" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="844.010775351266" y="636.757017867106" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;TextureRealWorldOffsetX&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="89d8247a-4b36-4a50-8d10-af7c95a8a2ad" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Material.SetMaterialAssetByAssetId" x="1373.30356075457" y="540.761061609506" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <ID value="0165cb8b-9780-4ac7-bc20-60e376ba6105" />
      <Name value="Material.SetMaterialAssetByAssetId" />
      <Description value="This node will set the material asset by asset id. Please make sure that the two input lists match in length. " />
      <Inputs>
        <Input value="TargetMaterial" />
        <Input value="AssetId" />
      </Inputs>
      <Outputs>
        <Output value="Material" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="c8fc420f-01e6-4d91-9bbc-9da375100709" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Material.SetMaterialAssetByMaterial" x="451.217015438152" y="636.756504266199" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <ID value="fc21f065-cc91-48c9-a5fb-02d2f0af721e" />
      <Name value="Material.SetMaterialAssetByMaterial" />
      <Description value="This node will copy a material asset element from source Material to a list of target materials. It esentially makes all materials inherit its Rendering Appearance. Useful for &quot;clay&quot; renderings. " />
      <Inputs>
        <Input value="TargetMaterial" />
        <Input value="SourceMaterial" />
      </Inputs>
      <Outputs>
        <Output value="Material" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <PythonNodeModels.PythonNode guid="472e3e0f-bc64-44c4-b84b-7304ca8b4acd" type="PythonNodeModels.PythonNode" nickname="Python Script" x="854.234500253516" y="-385.794129123048" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Visual import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

import sys

pyt_path = 'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

mat= IN[0]

mat2= UnwrapElement(mat)
doc = DocumentManager.Instance.CurrentDBDocument
AppearanceAsset = doc.GetElement(mat2.AppearanceAssetId)
AppearanceAssetid =AppearanceAsset.Id

RenderingAsset = AppearanceAsset.GetRenderingAsset()
#RenderingID = RenderingAsset.GetTypeId 

X = RenderingAsset.Name
Y = RenderingAsset.Title
Z = RenderingAsset.GetType()
ZA = RenderingAsset["common_Tint_color"]
ZB = ZA.GetValueAsColor()
ZC = RenderingAsset[UnifiedBitmap.UnifiedbitmapBitmap]
ZD = ZC.Name
ZE = RenderingAsset[Generic.GenericDiffuse]
ZF = ZE.Name
ZG = RenderingAsset[UnifiedBitmap.TextureScaleLock]
ZH = RenderingAsset[UnifiedBitmap.TextureRealWorldOffsetX]
ZI = ZH.Value
ZJ = RenderingAsset[UnifiedBitmap.UnifiedbitmapBitmap]
ZK = ZJ.Value
#TransactionManager.Instance.EnsureInTransaction(doc)
#TransactionManager.Instance.TransactionTaskDone()

OUT = mat2,AppearanceAsset, RenderingAsset, AppearanceAssetid</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="1e66b0b7-0bff-41ae-a4e4-dcaa5b12aebf" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1231.29259982187" y="59.9449925649299" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

# Import Element wrapper extension methods
import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

def ProcessList(_func, _list):
	return map(lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list)

def TryGetAssetId(mat):
	doc = DocumentManager.Instance.CurrentDBDocument
	appearanceId = mat.AppearanceAssetId
	if appearanceId != ElementId.InvalidElementId:
		appearanceElemn = doc.GetElement(appearanceId)
		return appearanceElemn
	else:
		return ElementId.InvalidElementId

def Unwrap(item):
	return UnwrapElement(item)

if isinstance(IN[0], list):
	elements = ProcessList(Unwrap, IN[0])
else:
	elements = [Unwrap(IN[0])]

try:
	errorReport = None
	output = ProcessList(TryGetAssetId, elements)
except:
	# if error accurs anywhere in the process catch it
	import traceback
	errorReport = traceback.format_exc()

#Assign your output to the OUT variable
if errorReport == None:
	OUT = output
else:
	OUT = errorReport</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="c0fbb23f-eaed-4d16-afa4-b7e6de999c63" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1509.54906437419" y="-532.780766623023" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Visual import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

import sys

pyt_path = 'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

mat1= IN[0]
var1 = "C:\3BM\60_revit_bibliotheek\00_rendermaterialen\Materials\160209_NLRSv2.5.2_textures\00_asfalt.jpg"

mat= UnwrapElement(mat1)
doc = DocumentManager.Instance.CurrentDBDocument
AppearanceAsset = doc.GetElement(mat.AppearanceAssetId)
RenderingAsset = AppearanceAsset.GetRenderingAsset()
AppearanceAssetid =AppearanceAsset.Id

A = RenderingAsset.Name
B = RenderingAsset.Title
C = RenderingAsset[UnifiedBitmap.UnifiedbitmapBitmap]
D = RenderingAsset[Generic.GenericDiffuse]
E = D.Name

F = RenderingAsset[UnifiedBitmap.TextureLinkTextureTransforms].Value
G = RenderingAsset[UnifiedBitmap.TextureOffsetLock].Value
H = RenderingAsset[UnifiedBitmap.TextureRealWorldOffsetX].GetConnectedProperty
I = RenderingAsset[UnifiedBitmap.TextureRealWorldOffsetY].Value
J = RenderingAsset[UnifiedBitmap.TextureRealWorldScaleX].Value
K = RenderingAsset[UnifiedBitmap.TextureRealWorldScaleY].Value
L = RenderingAsset[UnifiedBitmap.TextureScaleLock].Value
M = RenderingAsset[UnifiedBitmap.TextureURepeat].Value 
N = RenderingAsset[UnifiedBitmap.TextureVRepeat].Value 
O = RenderingAsset[UnifiedBitmap.TextureWAngle].Value 
P = RenderingAsset[UnifiedBitmap.UnifiedbitmapBitmap].Value 
Q = RenderingAsset[UnifiedBitmap.UnifiedbitmapInvert].Value 
R = RenderingAsset[UnifiedBitmap.UnifiedbitmapRGBAmount].Value 

OUT = mat,AppearanceAsset, RenderingAsset, A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="8aec64a0-d66a-41bc-9a59-e1c4ba7be0ec" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1158" y="-99" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="5;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="f38a0257-b829-4882-a5cf-44726409cb79" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2277.21228640442" y="104.553158195986" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="8">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="False" />
      <PortInfo index="5" default="False" />
      <PortInfo index="6" default="False" />
      <PortInfo index="7" default="False" />
      <Script>import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Visual import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

import sys

pyt_path = 'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

mat1= IN[0]
var1 = IN[1]
offsetX = IN[2]
offsetY = IN[3]
scaleX = IN[4]
scaleY = IN[5]
lockScale = IN[6]
angle = IN[7]

mat = UnwrapElement(mat1)
doc = DocumentManager.Instance.CurrentDBDocument

AppearanceAsset = doc.GetElement(mat.AppearanceAssetId)
RenderingAsset = AppearanceAsset.GetRenderingAsset()
AppearanceAssetid =AppearanceAsset.Id

TransactionManager.Instance.EnsureInTransaction(doc)

editScope = AppearanceAssetEditScope(doc)
AssetEditable = editScope.Start(AppearanceAssetid)

BitMapLocation = AssetEditable[UnifiedBitmap.UnifiedbitmapBitmap] #AssetProperty String Object
BitMapLocation.Value = var1

BitmapOffsetX = AssetEditable[UnifiedBitmap.TextureRealWorldOffsetX]
BitmapOffsetX.Value = offsetX

BitmapOffsetY = AssetEditable[UnifiedBitmap.TextureRealWorldOffsetY]
BitmapOffsetY.Value = offsetY

BitmapscaleX = AssetEditable[UnifiedBitmap.TextureRealWorldScaleX]
BitmapscaleX.Value = scaleX

BitmapScaleY = AssetEditable[UnifiedBitmap.TextureRealWorldScaleY]
BitmapScaleY.Value = scaleY

Scalelock = AssetEditable[UnifiedBitmap.TextureScaleLock]
Scalelock.Value = lockScale

TextureWAngle = AssetEditable[UnifiedBitmap.TextureWAngle]
TextureWAngle.Value = angle

editScope.Commit(IFailuresPreprocessor)

TransactionManager.Instance.TransactionTaskDone()

OUT = mat1</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="d119c56f-0d12-49ca-bdaf-21158c3e237f" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1297.49031430772" y="234.460562743655" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;C:/3BM/60_revit_bibliotheek/00_rendermaterialen/Materials/00_poriso.jpg&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="28129303-3784-4a74-87e1-23c965dace5c" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1834.69790020823" y="33.8794502729911" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="f7534324-00e2-4a20-afe9-5c4baa540f0f" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1981.3772910666" y="315.665028228502" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="50;" ShouldFocus="false" />
    <CoreNodeModels.Input.BoolSelector guid="1638ca48-3879-4fb2-bcd2-88852921a2fa" type="CoreNodeModels.Input.BoolSelector" nickname="LockScale" x="1984.50574986722" y="408.026613120634" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>True</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="3faa2ef1-3a99-4f32-95a6-5aa2f30584f1" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Angle" x="1987.59452540527" y="499.502534216217" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="50;" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="70184cf9-9ce0-4d09-b557-b0db93f923ba" start_index="0" end="c4dbb2f2-6e0a-49c1-afbd-296a32d6b610" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="70184cf9-9ce0-4d09-b557-b0db93f923ba" start_index="0" end="472e3e0f-bc64-44c4-b84b-7304ca8b4acd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="70184cf9-9ce0-4d09-b557-b0db93f923ba" start_index="0" end="1e66b0b7-0bff-41ae-a4e4-dcaa5b12aebf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="70184cf9-9ce0-4d09-b557-b0db93f923ba" start_index="0" end="c0fbb23f-eaed-4d16-afa4-b7e6de999c63" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="70184cf9-9ce0-4d09-b557-b0db93f923ba" start_index="0" end="f38a0257-b829-4882-a5cf-44726409cb79" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8ee843eb-5013-469a-911f-b0f992169a28" start_index="0" end="70184cf9-9ce0-4d09-b557-b0db93f923ba" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8aec64a0-d66a-41bc-9a59-e1c4ba7be0ec" start_index="0" end="c0fbb23f-eaed-4d16-afa4-b7e6de999c63" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d119c56f-0d12-49ca-bdaf-21158c3e237f" start_index="0" end="f38a0257-b829-4882-a5cf-44726409cb79" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f7534324-00e2-4a20-afe9-5c4baa540f0f" start_index="0" end="f38a0257-b829-4882-a5cf-44726409cb79" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f7534324-00e2-4a20-afe9-5c4baa540f0f" start_index="0" end="f38a0257-b829-4882-a5cf-44726409cb79" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f7534324-00e2-4a20-afe9-5c4baa540f0f" start_index="0" end="f38a0257-b829-4882-a5cf-44726409cb79" end_index="4" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f7534324-00e2-4a20-afe9-5c4baa540f0f" start_index="0" end="f38a0257-b829-4882-a5cf-44726409cb79" end_index="5" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1638ca48-3879-4fb2-bcd2-88852921a2fa" start_index="0" end="f38a0257-b829-4882-a5cf-44726409cb79" end_index="6" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3faa2ef1-3a99-4f32-95a6-5aa2f30584f1" start_index="0" end="f38a0257-b829-4882-a5cf-44726409cb79" end_index="7" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>