<Workspace Version="1.3.4.6666" X="132.252125858564" Y="-5.83122962627937" zoom="0.701238310094041" ScaleFactor="1" Name="GIS2BIM_ImportImageInView" Description="Import rasterimage in view" ID="69824e7d-ba97-4d5f-ae91-522bf95f083b" Category="GIS2BIM.Image">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="61105a33-3a2b-40e7-acc4-bfd607a7ccdd" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-53.6905015230006" y="408.36531761103" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="ImageWidthMeters: double" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="bdda4c01-3035-4a97-beeb-41bdf98d7763" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-53.6905015230006" y="493.301114670409" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="View" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e5705b26-bda9-452d-b9d9-20d34dd58e55" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-55.8153695806214" y="599.91380828258" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="ImagePath" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="0cf4656e-ca96-4450-b776-b0cbc9754ccb" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-51.0419243359557" y="674.336897978593" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//mm&#xD;&#xA;DeltaX: double=0" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="acb8f135-2c8c-4428-a451-552ba56d6e2b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-54.0801347721487" y="751.79246285835" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//mm&#xD;&#xA;DeltaY: double=0" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="0f8f9430-659b-4921-8924-7d90ba148303" type="PythonNodeModels.PythonNode" nickname="Python Script" x="358.035238664253" y="535.058128791368" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="7">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="False" />
      <PortInfo index="5" default="False" />
      <PortInfo index="6" default="False" />
      <Script># Main part used from Konrad K Sobon

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

clr.AddReference("RevitAPI")
import Autodesk 
from Autodesk.Revit.DB import * 
import System

# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

dataEnteringNode = IN

ImageWidthM=IN[0]
view=UnwrapElement(IN[1])
filePath=IN[2]
deltax=IN[3]
deltay=IN[4]
res = IN[5]
RunIt = IN[6]

width = ImageWidthM/0.3048
placement=System.Enum.GetValues(BoxPlacement)[0]
x = deltax/304.8
y = deltay/304.8
refPt = XYZ(x,y,0)

#Set Image Import Options

iio= ImageImportOptions()
	
message = None
if placement != None:
	iio.Placement = placement
if refPt !=None:
	iio.RefPoint = refPt
else: 
	message = "Please specify placement point."
if res !=None:
	iio.Resolution = res
else:
	iio.Resolution = 72
	

if RunIt:
	# Start Transaction
	doc = DocumentManager.Instance.CurrentDBDocument
	TransactionManager.Instance.EnsureInTransaction(doc)

	newElement = clr.StrongBox[Element]()
	elementOut = doc.Import(file = filePath, options = iio, view = view, element = newElement)
	
	#End Transaction
	TransactionManager.Instance.TransactionTaskDone()
	message = "Succes"
else: 
	message = "Set Runit to true"


#newElementID = newElement.Id

img = UnwrapElement(newElement)
w = img.LookupParameter("Width")
TransactionManager.Instance.EnsureInTransaction(doc)
w.Set(width)
TransactionManager.Instance.TransactionTaskDone()

newElement = newElement.Name

OUT = iio,message, newElement</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="692f6ead-f196-4916-9c6b-1e0e317b4cf7" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="70.218063197151" y="909.129831876016" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="300;" ShouldFocus="false" />
    <CoreNodeModels.Input.BoolSelector guid="2ca7e288-5242-4a45-ab3b-7911199e77d0" type="CoreNodeModels.Input.BoolSelector" nickname="Boolean" x="0.0400919920165279" y="990.195667727569" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>True</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="ba9bf56e-d914-47d6-b1b7-47c274baedb8" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="648.252846799851" y="535.299323949348" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="61105a33-3a2b-40e7-acc4-bfd607a7ccdd" start_index="0" end="0f8f9430-659b-4921-8924-7d90ba148303" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bdda4c01-3035-4a97-beeb-41bdf98d7763" start_index="0" end="0f8f9430-659b-4921-8924-7d90ba148303" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e5705b26-bda9-452d-b9d9-20d34dd58e55" start_index="0" end="0f8f9430-659b-4921-8924-7d90ba148303" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0cf4656e-ca96-4450-b776-b0cbc9754ccb" start_index="0" end="0f8f9430-659b-4921-8924-7d90ba148303" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="acb8f135-2c8c-4428-a451-552ba56d6e2b" start_index="0" end="0f8f9430-659b-4921-8924-7d90ba148303" end_index="4" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0f8f9430-659b-4921-8924-7d90ba148303" start_index="0" end="ba9bf56e-d914-47d6-b1b7-47c274baedb8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="692f6ead-f196-4916-9c6b-1e0e317b4cf7" start_index="0" end="0f8f9430-659b-4921-8924-7d90ba148303" end_index="5" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2ca7e288-5242-4a45-ab3b-7911199e77d0" start_index="0" end="0f8f9430-659b-4921-8924-7d90ba148303" end_index="6" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>